---
settings:
  name: ONTAP Cloud 9.3 release notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Cloud de ONTAP
    url: "/cloud-volumes-ontap-93-relnotes"
    version-number: '9.3'
  - name: Lo último de Cloud Volumes ONTAP
    url: "/cloud-volumes-ontap-relnotes"
    version-number: ''
  - name: Otras versiones
    url: https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-other-versions.html
    version-number: ''
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr
sidebar:
  entries:
  - title: Página principal de las notas de la versión
    url: "/index.html"
  - title: Novedades
    url: "/reference-new.html"
  - title: Configuraciones admitidas
    url: "/reference-supported-configs.html"
  - title: Límites de almacenamiento
    url: "/reference-storage-limits.html"
  - title: Problemas conocidos
    url: "/reference-issues.html"
  - title: Limitaciones conocidas
    url: "/reference-limitations.html"
  - title: Avisos legales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Manos a la obra
    links:
    - title: Novedades
      url: reference-new.html
  - title: Configuraciones y límites
    links:
    - title: Configuraciones admitidas
      url: reference-supported-configs.html
    - title: Límites de almacenamiento
      url: reference-storage-limits.html
    - title: Limitaciones
      url: reference-limitations.html
  - title: Blogs y comunidad
    links:
    - title: Comunidad de NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog de Cloud Central
      url: https://cloud.netapp.com/blog
    - title: Seminarios web sobre el cloud
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Documentación de All Cloud Manager
