---
sidebar: sidebar 
permalink: reference-supported-configs.html 
keywords: ec2, instance, type, vm, explore, standard, premium, byol, capacity, maximum, virtual machine, ontap cloud, supported, configurations 
summary: El cloud de ONTAP está disponible con diversas configuraciones en AWS y Azure. 
---
= Configuraciones admitidas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El cloud de ONTAP está disponible en AWS y Azure con dos opciones de precios: De pago por uso y con su propia licencia (BYOL). En el modelo de pago por uso, puede elegir entre tres configuraciones: Explorar, Standard o Premium.



== ONTAP Cloud para AWS

En AWS, puede poner en marcha ONTAP Cloud como un único sistema o como un par de alta disponibilidad.

[cols="h,d,d,d,d"]
|===
|  | Explorar | Estándar | Premium | BYOL 


| Tipos de instancia de EC2 | m4.xlarge  a| 
* m4.2xgrande
* r4.xlarge

 a| 
* c4.4xgrande
* c4.8x grande
* m4.4xgrande
* r4.2xgrande

 a| 
* c4.4xgrande
* c4.8x grande
* m4.xlarge
* m4.2xgrande
* m4.4xgrande
* r4.xlarge
* r4.2xgrande




| Almacenamiento subyacente 4+| SSD de uso general, SSD IOPS aprovisionados, HDD optimizados de rendimiento y HDD fríos, hasta 16 TIB por disco 


| Límite de capacidad de licencia | 2 TIB | 10 TIB | 368 TIB | 368 TIB por licencia 
|===
Notas:

. Las configuraciones de pago por uso no son compatibles con GovCloud (EE. UU.).
. Al seleccionar un tipo de instancia de EC2, puede especificar si es una instancia compartida o una instancia dedicada.
. El rendimiento de escritura mejorado es compatible cuando se utilizan unidades SSD de EBS con Cloud Standard, Premium y BYOL de ONTAP.
. La organización en niveles de los datos es compatible con Cloud Standard, Premium y BYOL de ONTAP.
. Si se habilita la clasificación por niveles de datos, el límite de capacidad de un sistema permanece igual. El límite de capacidad incluye tanto discos como almacenamiento de objetos.
. Para obtener soporte de región de AWS, consulte https://bluexp.netapp.com/cloud-volumes-global-regions["Regiones globales de Cloud Volumes"].




== ONTAP Cloud para Azure

En Azure, puede poner en marcha ONTAP Cloud como un sistema de nodos único.

[cols="h,d,d,d,d"]
|===
|  | Explorar | Estándar | Premium | BYOL 


| Tipos de máquinas virtuales | DS3_v2  a| 
* DS4_v2
* DS13_v2

 a| 
* DS5_v2
* DS14_v2

 a| 
* DS3_v2
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2




| Almacenamiento subyacente 4+| Discos duros estándar gestionados, discos SSD estándar gestionados y discos SSD Premium gestionados, hasta 32 TIB por disco 


| Límite de capacidad de licencia | 2 TIB | 10 TIB | 368 TIB | 368 TIB por licencia 
|===
Notas:

. Se admite el rendimiento de escritura mejorado cuando se utilizan discos de almacenamiento Premium de Azure con ONTAP Cloud Standard, Premium y BYOL, pero no cuando se utiliza el tipo de máquina virtual DS3_v2.
. Para obtener soporte de región de Azure, consulte https://bluexp.netapp.com/cloud-volumes-global-regions["Regiones globales de Cloud Volumes"].

