---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, alarms, cloudwatch, giveback, govcloud, detaching, encryption, snapmanager, features 
summary: Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente. 
---
= Limitaciones conocidas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las limitaciones conocidas identifican plataformas, dispositivos o funciones que no son compatibles con esta versión del producto o cuya interoperabilidad con esta no es óptima. Revise estas limitaciones detenidamente.



== Limitaciones generales

Las siguientes limitaciones se aplican al cloud de ONTAP en AWS y Azure.



=== Máximo de operaciones de replicación simultáneas

El número máximo de transferencias simultáneas de SnapMirror o SnapVault para Cloud Volumes ONTAP es 100 por nodo, independientemente del tipo de instancia o de tipo de máquina.



=== Cloud Manager debe completar las actualizaciones de software

Las actualizaciones de Cloud Volumes ONTAP se deben completar desde Cloud Manager. No debe actualizar Cloud Volumes ONTAP con System Manager o CLI. Hacerlo puede afectar a la estabilidad del sistema.



=== El cifrado no es compatible con los discos raíz y de arranque

Si habilitó una opción de su proveedor de cloud que cifra automáticamente todos los volúmenes o discos nuevos, debe deshabilitar temporalmente esa opción cuando ponga en marcha ONTAP Cloud. Si no lo hace, la puesta en marcha de cloud de ONTAP fallará. El cifrado no se admite en los discos raíz y de arranque del sistema ONTAP Cloud.



=== La implementación de la nube de ONTAP no se debe modificar desde la consola de su proveedor de la nube

Los cambios realizados en una configuración cloud de ONTAP desde la consola del proveedor de cloud dan como resultado una configuración no compatible. Cualquier cambio realizado en los recursos de cloud de ONTAP que cree y gestione Cloud Manager puede afectar a la estabilidad del sistema y a la capacidad de Cloud Manager de gestionar el sistema.



=== Los discos y los agregados deben gestionarse desde Cloud Manager

Todos los discos y agregados deben crearse y eliminarse directamente desde Cloud Manager. No debe realizar estas acciones desde otra herramienta de gestión. De esta manera, se puede afectar a la estabilidad del sistema, se puede obstaculizar la capacidad de añadir discos en el futuro y generar potencialmente cuotas redundantes para proveedores de cloud.



=== Limitación de la licencia de SnapManager

Las licencias de SnapManager por servidor son compatibles con ONTAP Cloud. No se admiten licencias por sistema de almacenamiento (suite SnapManager).



=== Funciones ONTAP no compatibles

Las siguientes funciones no son compatibles con ONTAP Cloud:

* Deduplicación inline a nivel de agregado
* Deduplicación en segundo plano a nivel de agregado
* Centro de mantenimiento de discos
* El saneamiento de disco
* Fibre Channel (FC)
* Flash Pool
* FlexCache
* Volúmenes de FlexGroup
* Infinite Volume
* Grupos de interfaces
* Conmutación al nodo de respaldo LIF de Itranode
* MetroCluster
* Multi-tenancy (solo se admite una SVM que sirve datos)
* Cifrado de volúmenes de NetApp
* RAID4, RAID-DP, RAID-TEC (compatible con RAID0)
* Procesador de servicios
* SnapLock
* SnapMirror síncrono
* VLAN




== Limitaciones conocidas para el cloud de ONTAP en AWS

Las siguientes limitaciones conocidas afectan a cloud de ONTAP en AWS.



=== Alarmas falsas notificadas por Amazon CloudWatch

La nube de ONTAP no libera CPU cuando está inactiva, por lo que Amazon CloudWatch puede generar una advertencia de CPU alta para la instancia de EC2 porque detecta un uso del 100 %. Puede ignorar esta alarma. El comando ONTAP statistics muestra el uso real de las CPU.



=== Los pares de alta disponibilidad cloud de ONTAP no admiten una devolución inmediata del almacenamiento

Cuando un nodo se reinicia, el partner debe sincronizar los datos para que puedan devolver el almacenamiento. El tiempo que tarda en resincronizar los datos depende de la cantidad de datos escritos por los clientes mientras el nodo estaba inactivo y de la velocidad de escritura de datos durante el momento de la restauración.



=== Limitaciones en la región de AWS GovCloud (EE. UU.

* Cloud Manager debe ponerse en marcha en una región de AWS GovCloud (EE. UU.) si desea iniciar instancias de Cloud Volumes ONTAP en cualquier región de AWS GovCloud (EE. UU.)
* La AMI de pago por uso de cloud de ONTAP no es compatible en la región de AWS GovCloud (EE. UU.)
* Cuando se implementa en la región de AWS GovCloud (EE. UU.), Cloud Manager no puede detectar clústeres de ONTAP en una configuración de almacenamiento privado de NetApp para Microsoft Azure ni una configuración de almacenamiento privado de NetApp para SoftLayer.




=== No se puede desvincular ni volver a asociar volúmenes de EBS

No se pueden desvincular un volumen de EBS de una instancia de ONTAP Cloud y, después, volver a conectarlo a otra instancia de cloud de ONTAP. Debe utilizar Cloud Manager para replicar datos entre instancias.



=== Limitaciones en el cifrado

* El movimiento de LUN no es compatible con sistemas que tienen habilitado el cifrado en cloud de ONTAP.
* ONTAP Cloud envía claves de cifrado a los administradores de claves incluso para los agregados que no pudo crear.
+
Debe eliminar manualmente las claves de los gestores de claves.


